# generated by datamodel-codegen:
#   filename:  APE_HE_Schema.json
#   timestamp: 2025-04-03T14:45:54+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Technique(Enum):
    STEP_MODE_XAS__X_RAY_ABSORPTION_SPECTROSCOPY_ = (
        'STEP-MODE XAS (X-RAY ABSORPTION SPECTROSCOPY)'
    )
    FAST_SCAN_XAS__X_RAY_ABSORPTION_SPECTROSCOPY_ = (
        'FAST-SCAN XAS (X-RAY ABSORPTION SPECTROSCOPY)'
    )
    XMCD__X_RAY_MAGNETIC_CIRCULAR_DICHROISM_ = (
        'XMCD (X-RAY MAGNETIC CIRCULAR DICHROISM)'
    )
    IV_CURVES = 'IV CURVES'
    field_2D_MAP = '2D MAP'


class Unit(Enum):
    min = 'min'
    ms = 'ms'
    s = 's'


class Duration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Duration of single scan by default in seconds'),
    ] = -9999
    unit: Optional[Unit] = 's'


class UserDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        Optional[str],
        Field(
            description='(Required) - Full name of the user in the format (Last name, First name)'
        ),
    ] = None
    affiliation: Annotated[
        Optional[str], Field(description='(Optional) - User institution affiliation')
    ] = None
    address: Annotated[
        Optional[str],
        Field(description='(Optional) - Full address of the user’s affiliation'),
    ] = None
    email: Annotated[Optional[str], Field(description='(Optional)- User email')] = None
    orcid: Annotated[
        Optional[str],
        Field(
            description='(Optional) - Open Researcher and Contributor ID expressed as a URI',
            pattern='^https://orcid\\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[X0-9]{1}$',
        ),
    ] = None


class Unit1(Enum):
    mV = 'mV'
    V = 'V'


class VoltageBias(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum voltage bias value by default in Volts (V)'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum voltage bias value by default in Volts (V)'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average voltage bias value by default in Volts (V)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit1],
        Field(description='(Required) - Unit of the voltage bias, default: V'),
    ] = 'V'


class Unit2(Enum):
    A_m = 'A/m'
    Oe = 'Oe'


class MagneticField(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pulse intensity of the magnetic field applied to switch the magnetization of the sample (Oe: Oersted)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit2],
        Field(
            description='(Required) - Unit of intensity of the magnetic field, default: Oersted.'
        ),
    ] = 'Oe'


class RemanentMagneticField(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Magnetic field remaining after removal of the pulse, i.e. during the measurement (Oe: Oersted)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit2],
        Field(
            description='(Required) - Unit of the remanent magnetic field, default: Oe.'
        ),
    ] = 'Oe'


class Situation(Enum):
    UHV = 'UHV'
    AMBIENT_PRESSURE_CELL = 'AMBIENT PRESSURE CELL'
    other = 'other'


class GasName(Enum):
    He = 'He'
    Ar = 'Ar'
    N2 = 'N2'
    O2 = 'O2'
    H2 = 'H2'
    CO = 'CO'
    CO2 = 'CO2'
    CH4 = 'CH4'
    C2H4 = 'C2H4'
    C2H6 = 'C2H6'
    C3H6 = 'C3H6'
    other = 'other'


class GasFluxItem(BaseModel):
    gas_name: Annotated[
        Optional[GasName],
        Field(
            description="Select the gas name from the predefined list. For 'other', specify the molecular formula."
        ),
    ] = None
    value: Annotated[
        Optional[float], Field(description='(Required)- The gas flux value in ml/min')
    ] = -9999
    unit: Annotated[
        Optional[str], Field(description='(Required)- Unit of the measured gas flux')
    ] = 'ml/min'
    gas_formula: Annotated[
        Optional[str],
        Field(description='The molecular formula of the gas if not listed'),
    ] = None


class Unit4(Enum):
    field_C = '°C'
    field_F = '°F'
    K = 'K'


class StartTemperatureDetails(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - The starting temperature value by default in Kelvin (K)'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit4],
        Field(
            description='(Required) - The unit of the starting temperature, default: K.'
        ),
    ] = 'K'


class EndTemperatureDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - The ending temperature value by default in Kelvin (K)'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit4],
        Field(
            description='(Required) - The unit of the ending temperature, default: K.'
        ),
    ] = 'K'


class Unit6(Enum):
    bar = 'bar'
    Pa = 'Pa'
    kPa = 'kPa'
    Torr = 'Torr'
    atm = 'atm'
    mbar = 'mbar'


class PressureDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pressure value in the measurement situation by default in mbar'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit6],
        Field(
            description='(Required) - Unit of the pressure measurement, default: mbar.'
        ),
    ] = 'mbar'


class Unit7(Enum):
    m = 'm'
    cm = 'cm'
    mm = 'mm'


class X(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum value of the position along the x-axis'
        ),
    ] = -9999
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum value of the position along the x-axis'
        ),
    ] = -9999
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average value of the position along the x-axis'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit7],
        Field(
            description='(Required) - Unit of measurement for the x-axis position, default: mm.'
        ),
    ] = 'mm'


class Y(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum value of the position along the y-axis'
        ),
    ] = -9999
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum value of the position along the y-axis'
        ),
    ] = -9999
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average value of the position along the y-axis'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit7],
        Field(
            description='(Required) - Unit of measurement for the y-axis position, default: mm.'
        ),
    ] = 'mm'


class Z(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Position value along the z-axis'),
    ] = -9999
    unit: Annotated[
        Optional[Unit7],
        Field(
            description='(Required) - Unit of measurement for the z-axis position, default: mm'
        ),
    ] = 'mm'


class Unit10(Enum):
    radians = 'radians'
    degrees = 'degrees'


class Theta(BaseModel):
    value: Annotated[
        Optional[float], Field(description='(Required) - Rotation angle value')
    ] = -9999
    unit: Annotated[
        Optional[Unit10],
        Field(
            description='(Required) - Unit of measurement for the rotation angle, default: degrees.'
        ),
    ] = 'degrees'


class Phi(BaseModel):
    value: Annotated[
        Optional[float], Field(description='(Required) - Rotation angle value')
    ] = -9999
    unit: Annotated[
        Optional[Unit10],
        Field(
            description='(Required) - Unit of measurement for the rotation angle, default: degrees.'
        ),
    ] = 'degrees'


class TransformationsDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: Annotated[
        Optional[X],
        Field(
            description='(Optional)- Position along the beam direction by default in mm'
        ),
    ] = None
    y: Annotated[
        Optional[Y],
        Field(
            description='(Optional)- Axis perpendicular to the beam by default in millimeters (mm)'
        ),
    ] = None
    z: Annotated[
        Optional[Z],
        Field(
            description='(Optional)- Vertical axis position by default in millimeters (mm)'
        ),
    ] = None
    theta: Annotated[
        Optional[Theta],
        Field(
            description='(Optional)- Rotation angle around the z-axis by default in degrees'
        ),
    ] = None
    phi: Annotated[
        Optional[Phi],
        Field(
            description='(Optional)- Rotation angle around the x-axis by default in degrees'
        ),
    ] = None


class Unit12(Enum):
    eV = 'eV'
    keV = 'keV'
    MeV = 'MeV'
    GeV = 'GeV'


class Energy(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Value of the beam energy by default in giga-electronvolt (GeV).'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit12],
        Field(
            description='(Required) - Unit of measurement for the beam energy, default: GeV.'
        ),
    ] = 'GeV'


class Unit13(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    A = 'A'
    mA = 'mA'


class Current(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Ring current value by default in milliamperes (mA)'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit13],
        Field(
            description='(Required) - Unit of measurement for the ring current, default: mA.'
        ),
    ] = 'mA'


class SourceDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        Optional[str],
        Field(description='(Required)- Default value: Synchrotron X-ray source'),
    ] = 'Synchrotron X-ray source'
    name: Annotated[
        Optional[str],
        Field(description='(Required)- Default value: Elettra-Sincrotrone Trieste'),
    ] = 'Elettra-Sincrotrone Trieste'
    probe: Annotated[
        Optional[str], Field(description='(Required)- Default value: X-ray')
    ] = 'X-ray'
    energy: Annotated[
        Optional[Energy], Field(description='(Required) - Details of the beam energy.')
    ] = None
    current: Annotated[
        Optional[Current],
        Field(description='(Required) - Details on Ring current measurement'),
    ] = None


class Unit14(Enum):
    keV = 'keV'
    MeV = 'MeV'
    GeV = 'GeV'
    eV = 'eV'


class Energy1(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Optional) - Minimun value of Photon energy by default in electronvolts (eV).'
        ),
    ] = -9999
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum value of Photon energy by default in electronvolts (eV).'
        ),
    ] = -9999
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average value of Photon energy by default in electronvolts (eV).'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit14],
        Field(
            description='(Required) - Unit of measurement for photon energy, default: eV'
        ),
    ] = 'eV'


class Unit15(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class IntegrationTime(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Optional) - Integration time value by default in milliseconds (ms)'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit15],
        Field(
            description='(Required) - Unit of measurement for integration time, default: ms.'
        ),
    ] = 'ms'


class Mirror(Enum):
    A = 'A'
    B = 'B'


class Value(Enum):
    number_1800 = 1800
    number_900 = 900


class Unit16(Enum):
    lines_mm = 'lines/mm'


class Period(BaseModel):
    value: Annotated[
        Optional[Value],
        Field(
            description='(Required) - Period value by default in lines per millimeter'
        ),
    ] = 1800
    unit: Annotated[
        Optional[Unit16],
        Field(description='(Required) - Unit of measurement for the period'),
    ] = 'lines/mm'


class GratingDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mirror: Annotated[
        Optional[Mirror],
        Field(description='(Required) - Mirror type used in the grating system'),
    ] = 'A'
    period: Annotated[
        Optional[Period], Field(description='(Required) - Grating period or spacing')
    ] = None


class Unit17(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class ElectrometerCurrentRange(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit17], Field(description='(Required) - Unit of the current range')
    ] = 'A'


class Data(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit17],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataPositiveMagneticField(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) with positive magnetic field'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with positive magnetic field'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with positive magnetic field'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit17],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataNegativeMagneticField(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) with negative magnetic field'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with negative magnetic field'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with negative magnetic field'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit17],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class IncomingBeamElectrometerDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the electrometer, default: 'Keithley 6517b Electrometer'"
        ),
    ] = 'Keithley 6517b Electrometer'
    NPLC: Annotated[
        Optional[int], Field(description='(Required) - Number of power line cycles')
    ] = None
    electrometer_current_range: Annotated[
        Optional[ElectrometerCurrentRange],
        Field(description='(Required) - Current range of the electrometer'),
    ] = None
    data: Annotated[
        Optional[Data],
        Field(
            description='(Optional) - Current at the entry of the endstation, measured from a tantalum (Ta) mesh covered with 200 nm of gold (Au), after the interaction with the X-ray beam'
        ),
    ] = None
    data_positive_magnetic_field: Annotated[
        Optional[DataPositiveMagneticField],
        Field(
            description='(Optional) - Current at the entry of the endstation, measured from a tantalum (Ta) mesh covered with 200 nm of gold (Au), after the interaction with the X-ray beam, with positive magnetic field applied on the sample'
        ),
    ] = None
    data_negative_magnetic_field: Annotated[
        Optional[DataNegativeMagneticField],
        Field(
            description='(Optional) - Current at the entry of the endstation, measured from a tantalum (Ta) mesh covered with 200 nm of gold (Au), after the interaction with the X-ray beam, with negative magnetic field applied on the sample'
        ),
    ] = None


class Unit21(Enum):
    mV = 'mV'
    V = 'V'


class ElectrometerVoltageRange(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Voltage range value by default in Volts (V)'),
    ] = None
    unit: Annotated[
        Optional[Unit21], Field(description='(Required) - Unit of the voltage range')
    ] = 'V'


class VoltageBias1(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum voltage bias value by default in Volts (V)'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum voltage bias value by default in Volts (V)'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average voltage bias value by default in Volts (V)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit21], Field(description='(Required) - Unit of the voltage bias')
    ] = 'V'


class Unit23(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class ElectrometerCurrentRange1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit23], Field(description='(Required) - Unit of the current range')
    ] = 'A'


class Data1(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataPositiveMagneticField1(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataNegativeMagneticField1(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class SampleCurrentElectrometerDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the electrometer, default: 'Keithley 6517b Electrometer'"
        ),
    ] = 'Keithley 6517b Electrometer'
    NPLC: Annotated[
        Optional[int], Field(description='(Required) - Number of power line cycles')
    ] = None
    electrometer_voltage_range: Annotated[
        Optional[ElectrometerVoltageRange],
        Field(description='(Optional) - Voltage range of the electrometer'),
    ] = None
    voltage_bias: Annotated[
        Optional[VoltageBias1], Field(description='(Optional) - Voltage bias')
    ] = None
    electrometer_current_range: Annotated[
        Optional[ElectrometerCurrentRange1],
        Field(description='(Required) - Current range of the electrometer'),
    ] = None
    data: Annotated[
        Optional[Data1],
        Field(
            description='(Optional) - Current measured from the sample after the interaction with the X-ray beam'
        ),
    ] = None
    data_positive_magnetic_field: Annotated[
        Optional[DataPositiveMagneticField1],
        Field(
            description='(Optional) - Current measured from the sample after the interaction with the X-ray beam, with positive magnetic field applied on the sample'
        ),
    ] = None
    data_negative_magnetic_field: Annotated[
        Optional[DataNegativeMagneticField1],
        Field(
            description='(Optional) - Minimum current measured from the sample after the interaction with the X-ray beam, with negative magnetic field applied on the sample'
        ),
    ] = None


class ElectrometerCurrentRange2(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit23], Field(description='(Required) - Unit of the current range')
    ] = 'A'


class Data2(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataPositiveMagneticField2(BaseModel):
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class DataNegativeMagneticField2(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current measurement'),
    ] = 'A'


class ReferenceCurrentElectrometerDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the electrometer, default: 'Keithley 6517b Electrometer'"
        ),
    ] = 'Keithley 6517b Electrometer'
    NPLC: Annotated[
        Optional[int], Field(description='(Required) - Number of power line cycles')
    ] = None
    electrometer_current_range: Annotated[
        Optional[ElectrometerCurrentRange2],
        Field(description='(Required) - Current range of the electrometer'),
    ] = None
    data: Annotated[
        Optional[Data2],
        Field(
            description='(Optional) - Current measured on the reference powder after the interaction with the X-ray beam'
        ),
    ] = None
    data_positive_magnetic_field: Annotated[
        Optional[DataPositiveMagneticField2],
        Field(
            description='(Optional) - Current measured on the reference powder after the interaction with the X-ray beam, with positive magnetic field applied on the sample'
        ),
    ] = None
    data_negative_magnetic_field: Annotated[
        Optional[DataNegativeMagneticField2],
        Field(
            description='(Optional) - Current measured on the reference powder after the interaction with the X-ray beam, with negative magnetic field applied on the sample'
        ),
    ] = None


class PicoammeterCurrentRange(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit23],
        Field(description='(Required) - Unit of the current range, default: A.'),
    ] = 'A'


class Unit32(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class IntegrationTime1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Integration time value by default in milliseconds (ms)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit32],
        Field(description='(Required) - Unit of the integration time, default: ms.'),
    ] = 'ms'


class Unit33(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class Data3(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) at the entry of the endstation'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit33],
        Field(description='(Required) - Unit of the current measurement, default: A.'),
    ] = 'A'


class IncomingBeamPicoammeterDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the picoammeter, default: 'AH501B Picoammeter'"
        ),
    ] = 'AH501B Picoammeter'
    picoammeter_current_range: Annotated[
        Optional[PicoammeterCurrentRange],
        Field(description='(Required) - Current range of the picoammeter'),
    ] = None
    integration_time: Annotated[
        Optional[IntegrationTime1],
        Field(description='(Optional) - Amount of time over which data is acquired'),
    ] = None
    data: Annotated[
        Optional[Data3],
        Field(
            description='(Required) - Current at the entry of the endstation, measured from a tantalum (Ta) mesh covered with 200 nm of gold (Au), after the interaction with the X-ray beam'
        ),
    ] = None


class PicoammeterCurrentRange1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit33],
        Field(description='(Required) - Unit of the current range, default: A.'),
    ] = 'A'


class Unit35(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class IntegrationTime2(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Integration time value by default in milliseconds (ms)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit35],
        Field(description='(Required) - Unit of the integration time, default: ms.'),
    ] = 'ms'


class Unit36(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class Data4(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) measured from the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit36],
        Field(description='(Required) - Unit of the current measurement, default: A.'),
    ] = 'A'


class SampleCurrentPicoammeterDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the picoammeter, default: 'AH501B Picoammeter'"
        ),
    ] = 'AH501B Picoammeter'
    picoammeter_current_range: Annotated[
        Optional[PicoammeterCurrentRange1],
        Field(description='(Required) - Current range of the picoammeter'),
    ] = None
    integration_time: Annotated[
        Optional[IntegrationTime2],
        Field(description='(Optional) - Amount of time over which data is acquired'),
    ] = None
    data: Annotated[
        Optional[Data4],
        Field(
            description='(Required) - Current measured from the sample after the interaction with the X-ray beam'
        ),
    ] = None


class PicoammeterCurrentRange2(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Current range value by default in amperes (A)'),
    ] = None
    unit: Annotated[
        Optional[Unit36],
        Field(description='(Required) - Unit of the current range, default: A.'),
    ] = 'A'


class Unit38(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class IntegrationTime3(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Integration time value by default in milliseconds (ms)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit38],
        Field(description='(Required) - Unit of the integration time, default: ms.'),
    ] = 'ms'


class Unit39(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class Data5(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average current value by default in amperes (A) measured on the reference powder'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit39],
        Field(description='(Required) - Unit of the current measurement, default: A.'),
    ] = 'A'


class ReferenceCurrentPicoammeterDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the picoammeter, default: 'AH501B Picoammeter'"
        ),
    ] = 'AH501B Picoammeter'
    picoammeter_current_range: Annotated[
        Optional[PicoammeterCurrentRange2],
        Field(description='(Required) - Current range of the picoammeter'),
    ] = None
    integration_time: Annotated[
        Optional[IntegrationTime3],
        Field(description='(Optional) - Amount of time over which data is acquired'),
    ] = None
    data: Annotated[
        Optional[Data5],
        Field(
            description='(Required) - Current measured on the reference powder after the interaction with the X-ray beam'
        ),
    ] = None


class Unit40(Enum):
    ohm = 'ohm'


class Impedance(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Impedance value by default in ohm.'),
    ] = None
    unit: Annotated[
        Optional[Unit40],
        Field(description='(Required) - Unit of the impedance, default: ohm.'),
    ] = 'ohm'


class Coupling(Enum):
    AC = 'AC'
    DC = 'DC'


class Unit41(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class CountTime(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Count time value by default in milliseconds (ms)'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit41],
        Field(description='(Required) - Unit of the count time, default: ms.'),
    ] = 'ms'


class Unit42(Enum):
    mV = 'mV'
    V = 'V'


class Threshold(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Threshold value by default in mV.'),
    ] = None
    unit: Annotated[
        Optional[Unit42],
        Field(description='(Required) - Unit of the threshold, default: mV.'),
    ] = 'mV'


class Unit43(Enum):
    Counts = 'Counts'


class Data6(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description="(Required) - Minimum channeltron counts value by default in 'Counts' measured on the reference powder"
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description="(Required) - Maximum channeltron counts value by default in 'Counts' measured on the reference powder"
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description="(Required) - Average channeltron counts value by default in 'Counts' measured on the reference powder"
        ),
    ] = None
    unit: Annotated[
        Optional[Unit43],
        Field(
            description='(Required) - Unit of the channeltron counts measurement, default: Counts.'
        ),
    ] = 'Counts'


class Unit44(Enum):
    pA = 'pA'
    nA = 'nA'
    uA = 'uA'
    mA = 'mA'
    A = 'A'


class DataPositiveMagneticField3(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum channeltron count value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum channeltron count value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average channeltron count value by default in amperes (A) with positive magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit44],
        Field(description='(Required) - Unit of the channeltron count'),
    ] = 'A'


class DataNegativeMagneticField3(BaseModel):
    min_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Minimum channeltron count value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    max_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Maximum channeltron count value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    average_value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Average channeltron count value by default in amperes (A) with negative magnetic field applied on the sample'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit44],
        Field(description='(Required) - Unit of the channeltron count'),
    ] = 'A'


class ChanneltronCounterDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(
            description="(Required) - Description of the channeltron counter, default: 'HP53132A Counter'"
        ),
    ] = 'HP53132A Counter'
    amplifier_type: Annotated[
        Optional[str],
        Field(description="(Required) - Amplifier type, default: 'Channeltron'."),
    ] = 'Channeltron'
    impedance: Annotated[
        Optional[Impedance], Field(description='(Required) - Impedance details.')
    ] = None
    coupling: Annotated[
        Optional[Coupling],
        Field(description='(Required) - Any of these values (dropdown):'),
    ] = None
    count_time: Annotated[
        Optional[CountTime],
        Field(description='(Required) - Count time over which data is acquired'),
    ] = None
    threshold: Annotated[
        Optional[Threshold], Field(description='(Required) - Threshold details.')
    ] = None
    data: Annotated[
        Optional[Data6],
        Field(
            description='(Optional) - Channeltron counts from the sample after the interaction with the X-ray beam.'
        ),
    ] = None
    data_positive_magnetic_field: Annotated[
        Optional[DataPositiveMagneticField3],
        Field(
            description='(Optional) - Channeltron counts from the sample after the interaction with the X-ray beam, with positive magnetic field applied on the sample'
        ),
    ] = None
    data_negative_magnetic_field: Annotated[
        Optional[DataNegativeMagneticField3],
        Field(
            description='(Optional) - Channeltron counts from the sample after the interaction with the X-ray beam, with negative magnetic field applied on the sample'
        ),
    ] = None


class Unit46(Enum):
    m = 'm'
    cm = 'cm'
    mm = 'mm'


class Gap(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Gap value by default in millimeters (mm)'),
    ] = -9999
    unit: Annotated[
        Optional[Unit46], Field(description='(Required) - Unit of the gap')
    ] = 'mm'


class ExitSlitDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gap: Annotated[
        Optional[Gap],
        Field(description='(Required) - Gap information about the exit slit.'),
    ] = None


class Unit47(Enum):
    Oe = 'Oe'
    A_m = 'A/m'


class MagneticField1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pulse intensity of the magnetic field by default in Oersted (Oe).'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit47],
        Field(
            description='(Required) - Unit of the pulse intensity of the magnetic field, default: Oe.'
        ),
    ] = 'Oe'


class RemanentMagneticField1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Value of the remanent magnetic field by default in Oersted (Oe).'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit47],
        Field(
            description='(Required) - Unit of the remanent magnetic field, default: Oe.'
        ),
    ] = 'Oe'


class Unit49(Enum):
    min = 'min'
    s = 's'
    ms = 'ms'


class PrePulseTime(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pre-pulse time value by default in milliseconds (ms).'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit49],
        Field(description='(Required) - Unit of the pre-pulse time, default: ms.'),
    ] = 'ms'


class PulseTime(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pulse time value by default in milliseconds (ms).'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit49],
        Field(description='(Required) - Unit of the pulse time, default: ms.'),
    ] = 'ms'


class PostPulseTime(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Post-pulse time value by default in milliseconds (ms).'
        ),
    ] = None
    unit: Annotated[
        Optional[Unit49],
        Field(description='(Required) - Unit of the post-pulse time, default: ms.'),
    ] = 'ms'


class KepcoDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amplifier_type: Annotated[
        Optional[str],
        Field(description="(Required) - Amplifier type, default: 'Channeltron'."),
    ] = 'Channeltron'
    magnetic_field: Annotated[
        Optional[MagneticField1],
        Field(
            description='(Required) - Pulse intensity of the magnetic field applied to switch the magnetization of the sample.'
        ),
    ] = None
    remanent_magnetic_field: Annotated[
        Optional[RemanentMagneticField1],
        Field(
            description='(Optional) - Magnetic field remaining after removal of the pulse, i.e. during the measurement.'
        ),
    ] = None
    pre_pulse_time: Annotated[
        Optional[PrePulseTime],
        Field(
            description='(Optional) - Waiting time before applying the magnetic field pulse.'
        ),
    ] = None
    pulse_time: Annotated[
        Optional[PulseTime],
        Field(
            description='(Optional) - Time during which the magnetic field pulse is applied.'
        ),
    ] = None
    post_pulse_time: Annotated[
        Optional[PostPulseTime],
        Field(
            description='(Optional) - Time after removal of the magnetic field pulse, after which the measurement takes place.'
        ),
    ] = None


class Unit52(Enum):
    radians = 'radians'
    degrees = 'degrees'


class IncidentAngle(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Incident angle of the prefocusing mirror.'),
    ] = 1.5
    unit: Annotated[
        Optional[Unit52],
        Field(description='(Required) - Unit of the incident angle, default: degrees.'),
    ] = 'degrees'


class Unit53(Enum):
    m = 'm'
    cm = 'cm'
    mm = 'mm'


class Motor3EncoderPosition(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Motor 3 encoder position by default in millimeters (mm).'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit53],
        Field(description='(Required) - Unit of the motor 3 encoder position.'),
    ] = 'mm'


class Motor4EncoderPosition(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Motor 4 encoder position by default in millimeters (mm).'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit53],
        Field(description='(Required) - Unit of the motor 4 encoder position.'),
    ] = 'mm'


class Unit55(Enum):
    bar = 'bar'
    Pa = 'Pa'
    kPa = 'kPa'
    Torr = 'Torr'
    atm = 'atm'
    mbar = 'mbar'


class Pressure(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Pressure value in the prefocussing mirror by default in mbar.'
        ),
    ] = -9999
    unit: Annotated[
        Optional[Unit55],
        Field(
            description='(Required) - Unit of the pressure in the prefocusing mirror, default: mbar.'
        ),
    ] = 'mbar'


class Unit56(Enum):
    field_C = '°C'
    field_F = '°F'
    K = 'K'


class Temperature(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Temperature value of the prefocusing mirror.'),
    ] = -9999
    unit: Annotated[
        Optional[Unit56],
        Field(description='(Required) - Unit of the temperature, default: °C.'),
    ] = '°C'


class PrefocusingMirrorDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[
        Optional[str],
        Field(description='(Required) - Description of the prefocusing mirror.'),
    ] = 'First mirror of the beamline. Spherical shape, radius 302.1 m. Encoder positions of motors 3 and 4 are related to translation and pitch of the mirror.'
    incident_angle: Annotated[
        Optional[IncidentAngle],
        Field(description='(Required)- Incident angle by default in degrees.'),
    ] = None
    motor3_encoder_position: Annotated[
        Optional[Motor3EncoderPosition],
        Field(
            description='(Required) - Information about the motor 3 encoder position.'
        ),
    ] = None
    motor4_encoder_position: Annotated[
        Optional[Motor4EncoderPosition],
        Field(
            description='(Required) - Information about the motor 4 encoder position.'
        ),
    ] = None
    pressure: Annotated[
        Optional[Pressure],
        Field(description='(Required)- Pressure in the prefocusing mirror.'),
    ] = None
    temperature: Annotated[
        Optional[Temperature],
        Field(
            description='(Required)- Temperature of the prefocusing mirror by default in degree celcius.'
        ),
    ] = None


class Unit57(Enum):
    m = 'm'
    cm = 'cm'
    mm = 'mm'


class Gap1(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Gap value by default in millimeters (mm)'),
    ] = -9999
    unit: Annotated[
        Optional[Unit57], Field(description='(Required) - Unit of the gap')
    ] = 'mm'


class Phase(BaseModel):
    value: Annotated[
        Optional[float],
        Field(description='(Required) - Phase value by default in millimeters (mm)'),
    ] = -9999
    unit: Annotated[
        Optional[Unit57], Field(description='(Required) - Unit of the phase')
    ] = 'mm'


class MagneticWavelength(BaseModel):
    value: Annotated[
        Optional[float],
        Field(
            description='(Required) - Magnetic wavelength by default in millimeters (cm).'
        ),
    ] = 6
    unit: Annotated[
        Optional[Unit57],
        Field(description='(Required) - Unit of the magnetic wavelength.'),
    ] = 'cm'


class UndulatorDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        Optional[str], Field(description='(Required) - Type of device.')
    ] = 'undulator'
    gap: Annotated[
        Optional[Gap1],
        Field(description='(Required) - Gap information about the undulator.'),
    ] = None
    phase: Annotated[
        Optional[Phase],
        Field(description='(Required) - Phase information about the undulator.'),
    ] = None
    magnetic_wavelength: Annotated[
        Optional[MagneticWavelength],
        Field(description='(Required) - Information about the magnetic wavelength.'),
    ] = None


class SampleDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        Optional[str],
        Field(description='(Required) - Descriptive name of the sample or sample ID'),
    ] = None
    chemical_formula: Annotated[
        Optional[str],
        Field(description='(Required) - Chemical formular of the measured sample'),
    ] = None
    start_temperature: Annotated[
        Optional[StartTemperatureDetails],
        Field(description='(Required) - Details on the start temperature'),
    ] = None
    end_temperature: Annotated[
        Optional[EndTemperatureDetails],
        Field(description='(Required) - Details on the end temperature'),
    ] = None
    voltage_bias: Annotated[
        Optional[VoltageBias],
        Field(
            description='(Optional) - A reference link to the voltage bias value located at /entry/instrument/sample_current_electrometer:detector/voltage_bias'
        ),
    ] = None
    magnetic_field: Annotated[
        Optional[MagneticField],
        Field(
            description='(Optional) - A reference link to the value magnetic field located at /entry/instrument/kepco:magnetic_kicker/magnetic_field'
        ),
    ] = None
    remanent_magnetic_field: Annotated[
        Optional[RemanentMagneticField],
        Field(
            description='(Optional) - A reference link to the value of the remanent magnetic field located at /entry/instrument/kepco:magnetic_kicker/remanent_magnetic_field'
        ),
    ] = None
    situation: Annotated[
        Optional[Situation],
        Field(
            description='(Required) - Situation to be selected from the enumerated list'
        ),
    ] = 'other'
    gas_flux: Annotated[
        Optional[List[GasFluxItem]],
        Field(description='(Optional) - Details on the gas flux'),
    ] = None
    pressure: Annotated[
        Optional[PressureDetails],
        Field(
            description='(Required) - Details on the pressure in the measurement situation'
        ),
    ] = None
    transformations: Annotated[
        Optional[TransformationsDetails],
        Field(description='(Required) - Details on transformations'),
    ] = None


class MonochromatorDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    energy: Annotated[
        Optional[Energy1],
        Field(description='(Optional) - Photon energy setting for the monochromator'),
    ] = None
    integration_time: Annotated[
        Optional[IntegrationTime],
        Field(description='(Optional) - Integration time for measurements'),
    ] = None
    grating: Annotated[
        Optional[GratingDetails], Field(description='(Required) - Grading details')
    ] = None


class InstrumentDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[
        Optional[SourceDetails],
        Field(description='(Required) - Details on the input source'),
    ] = None
    monochromator: Annotated[
        Optional[MonochromatorDetails],
        Field(description='(Optional) - Monochromator details'),
    ] = None
    incoming_beam_electrometer: Annotated[
        Optional[SampleCurrentElectrometerDetails],
        Field(description='(Optional ) - Sample current electrometer details'),
    ] = None
    sample_current_electrometer: Annotated[
        Optional[SampleCurrentElectrometerDetails],
        Field(description='(Optional) - Sample current electrometer details'),
    ] = None
    reference_current_electrometer: Annotated[
        Optional[ReferenceCurrentElectrometerDetails],
        Field(description='(Optional) - Reference current electrometer details'),
    ] = None
    incoming_beam_picoammeter: Annotated[
        Optional[IncomingBeamPicoammeterDetails],
        Field(description='(Optional) - Incoming beam picoammeter details'),
    ] = None
    sample_current_picoammeter: Annotated[
        Optional[SampleCurrentPicoammeterDetails],
        Field(description='(Optional) - Sample current picoammeter details'),
    ] = None
    reference_current_picoammeter: Annotated[
        Optional[ReferenceCurrentPicoammeterDetails],
        Field(description='(Optional) - Reference current picoammeter details'),
    ] = None
    channeltron_counter: Annotated[
        Optional[ChanneltronCounterDetails],
        Field(description='(Optional) - Channeltron counter details'),
    ] = None
    exit_slit: Annotated[
        Optional[ExitSlitDetails], Field(description='(Required) - Exit slit details')
    ] = None
    kepco: Annotated[
        Optional[KepcoDetails], Field(description='(Optional) - Kepco details')
    ] = None
    prefocusing_mirror: Annotated[
        Optional[PrefocusingMirrorDetails],
        Field(description='(Required) - Prefocusing mirror details'),
    ] = None
    undulator: Annotated[
        Optional[UndulatorDetails], Field(description='(Required) - Undulator details')
    ] = None


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: Annotated[
        Optional[str],
        Field(
            description=' (Required)- Experiment title with the format: [YYYY]_[MM]_[DD]_ID'
        ),
    ] = None
    entry_identifier: Annotated[
        Optional[str],
        Field(
            description=' (Required)- Experiment number automatically assigned by the software'
        ),
    ] = None
    technique: Annotated[
        Optional[Technique],
        Field(
            description=' (Required)- Technique applied for the experiment to be selected between enumerated'
        ),
    ] = None
    start_time: Annotated[
        Optional[datetime],
        Field(
            description='(Required)- Start time of the measurement in the ISO8601 date/time stamp format [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss]±[hh]:[mm]'
        ),
    ] = None
    end_time: Annotated[
        Optional[datetime],
        Field(
            description='(Required)- End time of the measurement in the ISO8601 date/time stamp format [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss]±[hh]:[mm]'
        ),
    ] = None
    duration: Annotated[
        Optional[Duration], Field(description='(Required) - Duration of single scan')
    ] = None
    number_of_scans: Annotated[
        Optional[str], Field(description='(Optional) - Number of scans')
    ] = None
    definition: Annotated[
        Optional[str], Field(description='(Required) - Default value: NXxas')
    ] = 'NXxas'
    user: Annotated[
        Optional[UserDetails], Field(description='(Required) - User details')
    ] = None
    sample: Annotated[
        Optional[SampleDetails], Field(description='(Required) - Sample details')
    ] = None
    instrument: Annotated[
        Optional[InstrumentDetails],
        Field(description='(Required) - Instrument details'),
    ] = None


class ApeHe(BaseModel):
    entry: Optional[Entry] = None
